baseURL = "https://droidian.org/"
languageCode = "en-us"
title = "Droidian"
theme = "gohugo-theme-ananke"

[params]
  custom_css = ["css/custom.css", "css/fork-awesome.min.css"]

# Controls the navigation
[[menu.main]]
  identifier = "a"
  name = "Home"
  title = "home"
  url = "/"
  weight = -400

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog"
  url = "/blog"
  weight = -340

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  title = "Projects"
  url = "/dgf"
  weight = -330
  
[[menu.main]]
  identifier = "images"
  name = "Images"
  title = "Images"
  url = "/dd"
  weight = -300
  
  
[[menu.main]]
  identifier = "bugtracker"
  name = "Bug Tracker"
  title = "Bug Tracker"
  url = "/ff"
  weight = -290
